sudo: required

language: node_js
node_js:
  - node

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.21.2
  LANG: ja_JP.utf-8

cache: yarn
dist: trusty

before_install:
  - sudo apt-get update
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - echo 'Canada/Pacific' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - sh env.sh local
  - docker-compose build
  - (cd ./nodejs/www/ && yarn)

script:
  - (cd ./nodejs/www/ && yarn flow)
  - (cd ./nodejs/www/ && yarn jest)
  - (cd ./nodejs/www/ && yarn jest --coverage)
  - cat ./nodejs/www/coverage/lcov.info | ./nodejs/www/node_modules/codeclimate-test-reporter/bin/codeclimate.js

after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
