version: "3"

services:
  www:
    shm_size: 256m
    build:
      context: ./nodejs/www
      dockerfile: www.Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
      - 9000:9000
      - 9001:9001
      - 9002:9002
      - 9003:9003
    volumes:
      - ./nodejs/www:/www:cached
      - /var/run/docker.sock:/var/run/docker.sock:cached
    environment:
      WWW_DOMAIN: ${WWW_DOMAIN}
      TZ: Asia/Tokyo
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    command: mongod
    volumes:
      - ./data/mongo:/data/db:cached
    environment:
      TZ: Asia/Tokyo

  nginx:
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile
    volumes:
      - ./nginx:/nginx:cached
      - ./nginx/localhost:/etc/nginx/conf.d
      - ./data/openssl:/var/www/openssl
    links:
      - www:www
    ports:
      - "80:80"
      - "443:443"
    environment:
      NODE_ENV: ${NODE_ENV}
      WWW_DOMAIN: ${WWW_DOMAIN}

  coturn:
    image: instrumentisto/coturn
    command:
      - -c=/etc/coturn/turnserver.conf
      - --log-file=stdout
      - --external-ip=0.0.0.0/$$(detect-external-ip)
    volumes:
      - ./coturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
